// Every component registered in components.js is checked, not just the ones a
// route reaches.
//
// The bundler only ever sees components reachable from a route, so a
// registered-but-unrouted component with a syntax error, a missing default
// export or a broken import was validated nowhere — it failed the first time
// somebody navigated to it.
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs-extra';
import path from 'node:path';
import { withTestProject } from './helpers/setup.js';
import { validateComponentProps } from '../commands/types/types.js';
import { getProjectRoot } from '../commands/utils/PathHelper.js';

/** Registers a component and writes its source, without touching any route. */
async function addUnroutedComponent(root, name, source) {
  const dir = path.join(root, 'src', 'Components', 'Visual', name);
  await fs.ensureDir(dir);
  await fs.writeFile(path.join(dir, `${name}.js`), source);

  const registryPath = path.join(root, 'src', 'Components', 'components.js');
  const registry = await fs.readFile(registryPath, 'utf8');
  await fs.writeFile(
    registryPath,
    registry.replace(/const components = \{/, `const components = {\n  "${name}": "Visual",`)
  );
}

const validate = (root) => validateComponentProps({ projectRoot: root || getProjectRoot(import.meta.url) });

describe('an unrouted component is still validated', () => {
  test('a syntax error is reported against its file', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(root, 'Orphan', 'export default class Orphan {\n  broken( {\n}');

      const { sourceErrors } = await validate(root);
      const found = sourceErrors.find((e) => e.component === 'Orphan');
      assert.ok(found, `Orphan must be reported, got ${JSON.stringify(sourceErrors)}`);
      assert.match(found.message, /Syntax error/);
      assert.match(found.message, /Orphan\.js:\d+:\d+/, 'with a jumpable location');
    });
  });

  test('a missing default export blocks the build', async () => {
    // Being in components.js means "this is a component", and the runtime loads
    // one with `const { default: myClass } = await import(...)`. Without a
    // default export the registration can never resolve — a broken entry, not a
    // style issue. components.js is auto-generated by scanning directories, so a
    // plain module parked at <Category>/<Name>/<Name>.js gets registered by
    // accident; the fix is to move it out of the components tree.
    await withTestProject(async (root) => {
      await addUnroutedComponent(root, 'NoDefault', 'export class NoDefault {}');

      const { sourceErrors } = await validate(root);
      const found = sourceErrors.find((e) => e.component === 'NoDefault');
      assert.ok(found, 'a component with no default export can never be built');
      assert.match(found.message, /no default export/);
      assert.match(found.message, /default: myClass/, 'and says why');
      assert.match(found.message, /move it out of the components tree/, 'and offers the other fix');
    });
  });

  test('an unresolved relative import is reported', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(
        root,
        'BadImport',
        "import { x } from './missing.js';\nexport default class BadImport { r() { return x; } }"
      );

      const { sourceErrors } = await validate(root);
      const found = sourceErrors.find((e) => e.component === 'BadImport');
      assert.ok(found, 'a broken import must be caught even with no route');
      assert.match(found.message, /cannot resolve "\.\/missing\.js"/);
      assert.match(found.message, /becomes `undefined` at runtime/);
    });
  });

  test('a healthy component produces nothing', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(root, 'Fine', 'export default class Fine { r() { return 1; } }');

      const { sourceErrors } = await validate(root);
      assert.equal(
        sourceErrors.filter((e) => e.component === 'Fine').length,
        0,
        `a valid component must not be flagged, got ${JSON.stringify(sourceErrors)}`
      );
    });
  });

  test('a relative asset import is not treated as broken', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(
        root,
        'WithAsset',
        "import logo from './logo.svg';\nexport default class WithAsset { r() { return logo; } }"
      );

      const { sourceErrors } = await validate(root);
      assert.equal(sourceErrors.filter((e) => e.component === 'WithAsset').length, 0);
    });
  });
});

describe('building an unregistered component warns without blocking', () => {
  test('an unknown name is a warning, not an error', async () => {
    // Components legitimately build OPTIONAL ones: the framework's own Button
    // does `if (this.icon) slice.build('Icon', ...)`, and a project that never
    // passes an icon has no reason to install Icon. Blocking the build on that
    // would reject a perfectly good project.
    await withTestProject(async (root) => {
      await addUnroutedComponent(
        root,
        'Typoed',
        "export default class Typoed { async init() { await slice.build('DoesNotExist'); } }"
      );

      const { sourceErrors, sourceWarnings } = await validate(root);
      assert.equal(sourceErrors.filter((e) => e.component === 'Typoed').length, 0,
        'it must not block the build');
      const warned = sourceWarnings.find((w) => w.component === 'Typoed');
      assert.ok(warned, 'but it must be surfaced');
      assert.match(warned.message, /DoesNotExist/);
      assert.match(warned.message, /if the component is optional, ignore this/i);
    });
  });

  test('building a registered component says nothing', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(
        root,
        'BuildsKnown',
        "export default class BuildsKnown { async init() { await slice.build('BuildsKnown'); } }"
      );

      const { sourceWarnings } = await validate(root);
      assert.equal(sourceWarnings.filter((w) => w.component === 'BuildsKnown').length, 0);
    });
  });

  test('a computed component name is not guessed at', async () => {
    await withTestProject(async (root) => {
      await addUnroutedComponent(
        root,
        'Dynamic',
        'export default class Dynamic { async init(n) { await slice.build(n); } }'
      );

      const { sourceWarnings } = await validate(root);
      assert.equal(sourceWarnings.filter((w) => w.component === 'Dynamic').length, 0);
    });
  });
});
